
export const SEND_DATA = "SEND_DATA"
export const ADD_ITEM = "ADD_ITEM"
export const UPDATE_ITEMNAME = "UPDATE_ITEMNAME"
export const UPDATE_ITEMDESCRIPTION = "UPDATE_ITEMDESCRIPTION"
export const UPDATE_ITEMQTY = "UPDATE_ITEMQTY"
export const UPDATE_ITEMRATE = "UPDATE_ITEMRATE"